export const gigsSeed = [
  {
    title: "Modern E-Commerce Website Development",
    description:
      "Looking for an experienced developer to build a full-stack e-commerce platform with React, Node.js, and MongoDB. The project includes product management, user authentication, payment integration with Stripe, and admin dashboard.",
    category: "Web Development",
    budget: { min: 2000, max: 5000 },
    skills: ["React", "Node.js", "MongoDB", "Stripe", "JavaScript"],
    postedBy: "freelancer-001",
    freelancerName: "Sarah Anderson",
    freelancerImage: "https://i.pravatar.cc/150?img=1",
    freelancerRating: 4.8,
    freelancerReviews: 245,
    deliveryTime: 30,
    status: "active",
    proposals: 12,
    views: 284,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop",
  },
  {
    title: "iOS App Development - Fitness Tracker",
    description:
      "Develop a comprehensive iOS fitness tracking application with real-time workout tracking, data visualization, and social features. Must have experience with Swift and HealthKit framework.",
    category: "Mobile Development",
    budget: { min: 3000, max: 7000 },
    skills: ["Swift", "iOS", "HealthKit", "Firebase"],
    postedBy: "freelancer-002",
    freelancerName: "Alex Chen",
    freelancerImage: "https://i.pravatar.cc/150?img=2",
    freelancerRating: 4.9,
    freelancerReviews: 312,
    deliveryTime: 45,
    status: "active",
    proposals: 8,
    views: 195,
    image: "https://images.unsplash.com/photo-1512941691920-25beb1d37e6d?w=500&h=300&fit=crop",
  },
  {
    title: "Professional Logo & Branding Design",
    description:
      "Need a talented designer to create a complete brand identity including logo design, color palette, typography guidelines, and brand guidelines document. Startup-focused with modern aesthetic.",
    category: "Design",
    budget: { min: 500, max: 1500 },
    skills: ["Graphic Design", "Branding", "Figma", "Adobe Creative Suite"],
    postedBy: "freelancer-003",
    freelancerName: "Maria Garcia",
    freelancerImage: "https://i.pravatar.cc/150?img=3",
    freelancerRating: 4.7,
    freelancerReviews: 189,
    deliveryTime: 14,
    status: "active",
    proposals: 34,
    views: 512,
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=300&fit=crop",
  },
  {
    title: "Content Writer - Tech Blog Articles",
    description:
      "Write 20 high-quality tech blog articles (1500-2000 words each) covering AI/ML topics, cloud computing, and DevOps. SEO-optimized content required with proper formatting and citations.",
    category: "Writing",
    budget: { min: 800, max: 2000 },
    skills: ["Content Writing", "SEO", "Technical Writing", "AI/ML Knowledge"],
    postedBy: "freelancer-004",
    freelancerName: "James Wilson",
    freelancerImage: "https://i.pravatar.cc/150?img=4",
    freelancerRating: 4.6,
    freelancerReviews: 156,
    deliveryTime: 30,
    status: "active",
    proposals: 15,
    views: 267,
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=500&h=300&fit=crop",
  },
  {
    title: "Social Media Marketing Campaign Strategy",
    description:
      "Create a comprehensive 3-month social media marketing strategy for a B2B SaaS company. Include content calendar, hashtag research, engagement tactics, and metrics for success.",
    category: "Marketing",
    budget: { min: 1200, max: 3000 },
    skills: ["Social Media Marketing", "Analytics", "Content Strategy", "LinkedIn"],
    postedBy: "freelancer-005",
    freelancerName: "Priya Sharma",
    freelancerImage: "https://i.pravatar.cc/150?img=5",
    freelancerRating: 4.9,
    freelancerReviews: 287,
    deliveryTime: 21,
    status: "active",
    proposals: 22,
    views: 401,
    image: "https://images.unsplash.com/photo-1460925895917-aaf19ac89472?w=500&h=300&fit=crop",
  },
  {
    title: "Data Analysis & Visualization Dashboard",
    description:
      "Build an interactive data analysis dashboard using Python and Tableau. Analyze sales data, customer behavior, and market trends. Deliver detailed insights with visualizations and recommendations.",
    category: "Data Analysis",
    budget: { min: 1500, max: 4000 },
    skills: ["Python", "Tableau", "SQL", "Data Analysis", "Statistics"],
    postedBy: "freelancer-006",
    freelancerName: "David Martinez",
    freelancerImage: "https://i.pravatar.cc/150?img=6",
    freelancerRating: 4.8,
    freelancerReviews: 234,
    deliveryTime: 28,
    status: "active",
    proposals: 9,
    views: 187,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&h=300&fit=crop",
  },
  {
    title: "Professional Video Editing & Motion Graphics",
    description:
      "Edit 5 promotional videos (3-5 minutes each) for our product launch. Include motion graphics, color grading, and background music. Delivery in 4K resolution.",
    category: "Video Editing",
    budget: { min: 1000, max: 2500 },
    skills: ["Video Editing", "Adobe Premiere Pro", "After Effects", "Motion Graphics"],
    postedBy: "freelancer-007",
    freelancerName: "Emma Johnson",
    freelancerImage: "https://i.pravatar.cc/150?img=7",
    freelancerRating: 4.7,
    freelancerReviews: 198,
    deliveryTime: 21,
    status: "active",
    proposals: 11,
    views: 234,
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=500&h=300&fit=crop",
  },
  {
    title: "Machine Learning Model Development",
    description:
      "Develop ML models for customer churn prediction. Requires data preprocessing, feature engineering, model training, and deployment. Deliverables include trained models and documentation.",
    category: "AI & Machine Learning",
    budget: { min: 2500, max: 6000 },
    skills: ["Python", "TensorFlow", "Scikit-learn", "Data Science", "ML"],
    postedBy: "freelancer-008",
    freelancerName: "Michael Khan",
    freelancerImage: "https://i.pravatar.cc/150?img=8",
    freelancerRating: 4.9,
    freelancerReviews: 301,
    deliveryTime: 35,
    status: "active",
    proposals: 7,
    views: 156,
    image: "https://images.unsplash.com/photo-1526374965328-7f5ae4e8a84e?w=500&h=300&fit=crop",
  },
  {
    title: "Full-Stack MERN Application",
    description:
      "Build a complete project management application using MongoDB, Express, React, and Node.js. Features: user authentication, project creation, task management, real-time notifications.",
    category: "Web Development",
    budget: { min: 2200, max: 5500 },
    skills: ["React", "Node.js", "MongoDB", "Express", "JavaScript"],
    postedBy: "freelancer-001",
    freelancerName: "Sarah Anderson",
    freelancerImage: "https://i.pravatar.cc/150?img=1",
    freelancerRating: 4.8,
    freelancerReviews: 245,
    deliveryTime: 42,
    status: "active",
    proposals: 10,
    views: 223,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop",
  },
  {
    title: "React Native App for E-Learning Platform",
    description:
      "Develop a cross-platform e-learning mobile app with video streaming, progress tracking, and offline access. Should work on both iOS and Android using React Native.",
    category: "Mobile Development",
    budget: { min: 3500, max: 8000 },
    skills: ["React Native", "Firebase", "JavaScript", "Mobile Development"],
    postedBy: "freelancer-002",
    freelancerName: "Alex Chen",
    freelancerImage: "https://i.pravatar.cc/150?img=2",
    freelancerRating: 4.9,
    freelancerReviews: 312,
    deliveryTime: 50,
    status: "active",
    proposals: 6,
    views: 142,
    image: "https://images.unsplash.com/photo-1512941691920-25beb1d37e6d?w=500&h=300&fit=crop",
  },
  {
    title: "UI/UX Design - Mobile App Redesign",
    description:
      "Redesign the user interface and experience for our mobile application. Create wireframes, prototypes, and high-fidelity mockups. Must include user testing insights and implementation guidelines.",
    category: "Design",
    budget: { min: 1200, max: 3000 },
    skills: ["UI Design", "UX Design", "Figma", "Prototyping", "User Research"],
    postedBy: "freelancer-003",
    freelancerName: "Maria Garcia",
    freelancerImage: "https://i.pravatar.cc/150?img=3",
    freelancerRating: 4.7,
    freelancerReviews: 189,
    deliveryTime: 25,
    status: "active",
    proposals: 18,
    views: 356,
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=300&fit=crop",
  },
  {
    title: "eBook Writing - Tech Career Guide",
    description:
      "Write a comprehensive eBook on career transitions in tech industry. 80-100 pages, 40,000+ words. Include practical tips, success stories, and actionable advice for career changers.",
    category: "Writing",
    budget: { min: 2000, max: 4000 },
    skills: ["Technical Writing", "Career Coaching", "eBook Writing", "Editing"],
    postedBy: "freelancer-004",
    freelancerName: "James Wilson",
    freelancerImage: "https://i.pravatar.cc/150?img=4",
    freelancerRating: 4.6,
    freelancerReviews: 156,
    deliveryTime: 60,
    status: "active",
    proposals: 5,
    views: 89,
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=500&h=300&fit=crop",
  },
  {
    title: "Digital Marketing Strategy & Execution",
    description:
      "Develop and execute a complete digital marketing strategy including email marketing, paid advertising, and analytics tracking. Target audience: tech startups. 6-month engagement.",
    category: "Marketing",
    budget: { min: 2500, max: 6000 },
    skills: ["Digital Marketing", "Google Ads", "Email Marketing", "Analytics"],
    postedBy: "freelancer-005",
    freelancerName: "Priya Sharma",
    freelancerImage: "https://i.pravatar.cc/150?img=5",
    freelancerRating: 4.9,
    freelancerReviews: 287,
    deliveryTime: 180,
    status: "active",
    proposals: 14,
    views: 289,
    image: "https://images.unsplash.com/photo-1460925895917-aaf19ac89472?w=500&h=300&fit=crop",
  },
  {
    title: "Advanced SQL & Database Optimization",
    description:
      "Optimize existing database queries and structure for better performance. Analyze current bottlenecks, implement indexing strategies, and provide performance benchmarks and documentation.",
    category: "Data Analysis",
    budget: { min: 1000, max: 2500 },
    skills: ["SQL", "Database Design", "Performance Optimization", "PostgreSQL"],
    postedBy: "freelancer-006",
    freelancerName: "David Martinez",
    freelancerImage: "https://i.pravatar.cc/150?img=6",
    freelancerRating: 4.8,
    freelancerReviews: 234,
    deliveryTime: 14,
    status: "active",
    proposals: 8,
    views: 127,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&h=300&fit=crop",
  },
  {
    title: "Animated Explainer Video Production",
    description:
      "Create a 2-3 minute animated explainer video for SaaS product. Include script writing, storyboarding, animation, voiceover, and sound design. Delivery in HD and 4K.",
    category: "Video Editing",
    budget: { min: 1500, max: 3500 },
    skills: ["Animation", "Video Production", "Scriptwriting", "Sound Design"],
    postedBy: "freelancer-007",
    freelancerName: "Emma Johnson",
    freelancerImage: "https://i.pravatar.cc/150?img=7",
    freelancerRating: 4.7,
    freelancerReviews: 198,
    deliveryTime: 28,
    status: "active",
    proposals: 9,
    views: 167,
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=500&h=300&fit=crop",
  },
  {
    title: "Deep Learning Model - Computer Vision",
    description:
      "Build a deep learning model for image recognition and object detection. Use TensorFlow/PyTorch. Include training, validation, and deployment on cloud infrastructure (AWS/GCP).",
    category: "AI & Machine Learning",
    budget: { min: 3500, max: 8000 },
    skills: ["Python", "TensorFlow", "PyTorch", "Computer Vision", "Deep Learning"],
    postedBy: "freelancer-008",
    freelancerName: "Michael Khan",
    freelancerImage: "https://i.pravatar.cc/150?img=8",
    freelancerRating: 4.9,
    freelancerReviews: 301,
    deliveryTime: 45,
    status: "active",
    proposals: 5,
    views: 98,
    image: "https://images.unsplash.com/photo-1526374965328-7f5ae4e8a84e?w=500&h=300&fit=crop",
  },
  {
    title: "DevOps Setup - Docker & Kubernetes",
    description:
      "Set up complete DevOps infrastructure with Docker containerization and Kubernetes orchestration. Include CI/CD pipeline setup, monitoring, and documentation.",
    category: "Cloud Computing",
    budget: { min: 2000, max: 5000 },
    skills: ["Docker", "Kubernetes", "CI/CD", "AWS", "DevOps"],
    postedBy: "freelancer-001",
    freelancerName: "Sarah Anderson",
    freelancerImage: "https://i.pravatar.cc/150?img=1",
    freelancerRating: 4.8,
    freelancerReviews: 245,
    deliveryTime: 28,
    status: "active",
    proposals: 11,
    views: 198,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop",
  },
]
