export const freelancersSeed = [
  {
    uid: "freelancer-001",
    name: "Sarah Anderson",
    email: "sarah.anderson@example.com",
    profileImage: "https://i.pravatar.cc/150?img=1",
    rating: 4.8,
    reviews: 245,
    roles: { freelancer: true },
  },
  {
    uid: "freelancer-002",
    name: "Alex Chen",
    email: "alex.chen@example.com",
    profileImage: "https://i.pravatar.cc/150?img=2",
    rating: 4.9,
    reviews: 312,
    roles: { freelancer: true },
  },
  {
    uid: "freelancer-003",
    name: "Maria Garcia",
    email: "maria.garcia@example.com",
    profileImage: "https://i.pravatar.cc/150?img=3",
    rating: 4.7,
    reviews: 189,
    roles: { freelancer: true },
  },
  {
    uid: "freelancer-004",
    name: "James Wilson",
    email: "james.wilson@example.com",
    profileImage: "https://i.pravatar.cc/150?img=4",
    rating: 4.6,
    reviews: 156,
    roles: { freelancer: true },
  },
  {
    uid: "freelancer-005",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    profileImage: "https://i.pravatar.cc/150?img=5",
    rating: 4.9,
    reviews: 287,
    roles: { freelancer: true },
  },
  {
    uid: "freelancer-006",
    name: "David Martinez",
    email: "david.martinez@example.com",
    profileImage: "https://i.pravatar.cc/150?img=6",
    rating: 4.8,
    reviews: 234,
    roles: { freelancer: true },
  },
  {
    uid: "freelancer-007",
    name: "Emma Johnson",
    email: "emma.johnson@example.com",
    profileImage: "https://i.pravatar.cc/150?img=7",
    rating: 4.7,
    reviews: 198,
    roles: { freelancer: true },
  },
  {
    uid: "freelancer-008",
    name: "Michael Khan",
    email: "michael.khan@example.com",
    profileImage: "https://i.pravatar.cc/150?img=8",
    rating: 4.9,
    reviews: 301,
    roles: { freelancer: true },
  },
]
